arm:
  type: ur10
sensors:
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.599993, 4.742018, 0.910000]
      rpy: [0, 0, 'pi']
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [1.21, 4.0, 1.424088]
      rpy: [0, 'pi/2', 0]
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [-0.70, -1.33, 1.36]
      rpy: [1.55, 1.289, 0]